# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'InternManager' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  
#  pod 'YYKit'
#  #集成环信SDK
#  pod 'Hyphenate'
#  #集成环信EaseUI
#  pod 'EaseUI', :git => 'https://github.com/easemob/easeui-ios-hyphenate-cocoapods.git', :tag => '3.3.2'
  pod 'MJRefresh'
  pod 'DateToolsSwift'
  pod 'SnapKit', '~> 3.2.0' #自动布局
  pod 'Hero'  #转场动画
  pod 'Moya'  #网络请求
  pod 'Moya/RxSwift'     #rx
  pod 'RxSwift',    '~> 3.0'  #响应式编程
  pod 'RxCocoa',    '~> 3.0'  #响应式编程组件
  pod 'SwiftyJSON'            #JSON处理
  pod 'Then'                  #方便开发
  pod 'PromiseKit', '~> 4.0'   #简化异步操作
  pod 'ObjectMapper', '~> 2.2'   #json->model
  pod 'Kingfisher', '~> 3.0'    #image
#  pod 'RealmSwift'
  pod 'HanekeSwift', :git => 'https://github.com/Haneke/HanekeSwift', :branch => 'feature/swift-3'
  pod 'QQ_XGPush'         # 腾讯信鸽推送
#  pod 'AMap3DMap'           # 高德地图
#  pod 'AMapSearch'           # 高德地图
#  pod 'AMapLocation'        # 高德地图
  pod 'IQKeyboardManagerSwift'    #键盘
  pod 'NVActivityIndicatorView'   #转圈
  pod 'CryptoSwift'             #加密算法
  pod 'SVProgressHUD'           #提示
  pod 'LLCycleScrollView'       #轮播
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'    #颜色
  pod 'ImagePicker','~> 2.0.0'
  pod 'Lightbox'
  
  pod 'RongCloudIM/IMLib', '~> 2.8.3'
  pod 'RongCloudIM/IMKit', '~> 2.8.3'
  # Pods for InternManager

  target 'InternManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InternManagerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
